src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $poids;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dangereux;

    /**
     * @ORM\ManyToOne(targetEntity=Famille::class, inversedBy="animaux")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\ManyToMany(targetEntity=Continent::class, mappedBy="animaux")
     */
    private $continents;

    /**
     * @ORM\OneToMany(targetEntity=Dispose::class, mappedBy="animal")
     */
    private $disposes;

    public function __construct()
    {
        $this->continents = new ArrayCollection();
        $this->disposes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPoids(): ?int
    {
        return $this->poids;
    }

    public function setPoids(int $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getDangereux(): ?bool
    {
        return $this->dangereux;
    }

    public function setDangereux(bool $dangereux): self
    {
        $this->dangereux = $dangereux;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    /**
     * @return Collection|Continent[]
     */
    public function getContinents(): Collection
    {
        return $this->continents;
    }

    public function addContinent(Continent $continent): self
    {
        if (!$this->continents->contains($continent)) {
            $this->continents[] = $continent;
            $continent->addAnimaux($this);
        }

        return $this;
    }

    public function removeContinent(Continent $continent): self
    {
        if ($this->continents->removeElement($continent)) {
            $continent->removeAnimaux($this);
        }

        return $this;
    }

    /**
     * @return Collection|Dispose[]
     */
    public function getDisposes(): Collection
    {
        return $this->disposes;
    }

    public function addDispose(Dispose $dispose): self
    {
        if (!$this->disposes->contains($dispose)) {
            $this->disposes[] = $dispose;
            $dispose->setAnimal($this);
        }

        return $this;
    }

    public function removeDispose(Dispose $dispose): self
    {
        if ($this->disposes->removeElement($dispose)) {
            // set the owning side to null (unless already changed)
            if ($dispose->getAnimal() === $this) {
                $dispose->setAnimal(null);
            }
        }

        return $this;
    }
}

src/Entity/Famille.php
<?php

namespace App\Entity;

use App\Repository\FamilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FamilleRepository::class)
 */
class Famille
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Animal::class, mappedBy="famille")
     */
    private $animaux;

    public function __construct()
    {
        $this->animaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Animal[]
     */
    public function getAnimaux(): Collection
    {
        return $this->animaux;
    }

    public function addAnimaux(Animal $animaux): self
    {
        if (!$this->animaux->contains($animaux)) {
            $this->animaux[] = $animaux;
            $animaux->setFamille($this);
        }

        return $this;
    }

    public function removeAnimaux(Animal $animaux): self
    {
        if ($this->animaux->removeElement($animaux)) {
            // set the owning side to null (unless already changed)
            if ($animaux->getFamille() === $this) {
                $animaux->setFamille(null);
            }
        }

        return $this;
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

//use App\Entity\Animal;

use App\Entity\Animal;
use App\Repository\AnimalRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AnimalController extends AbstractController
{
    /**
     * @Route("/", name="animaux")
     */
    // public function index(): Response
    // {
    //     /**
    //      * nous allons utiliser le repository qui permet de récupérer des informations de la BdD
    //      * Pour cela nous utiliserons doctrine pour récupérer le répository et enfin nous pouvons 
    //      * utiliser la fonction de base du repository findAll qui va permettre de récupérer tous les animaux
    //      * Une fois que nous avons récupérer tous les animaux nous pourons transmettre la variable comme une
    //      * information dans le template qui se chargera d'afficher les animaux.
    //      */
    //     //Récupération du répository lié à l'entity animal
    //     $repository = $this->getDoctrine()->getRepository(Animal::class);//dans l'argument en indique à partir de quelle classe on veut récupérer le répository
    //     $animaux = $repository->findAll();
    //     //En renvoie la propriété "animaux" qui sera ensuite utilisable en twig graçe à la syntaxe json
    //     return $this->render('animal/index.html.twig', [
    //         "animaux"=>$animaux
    //     ]);
    // }
    public function index(AnimalRepository $repository): Response
    {
        /**
         * on poura ne pas utiliser la ligne 26 en ceci en utilisons l'injection de dépondence
         * càd que dans l'argument de la fonction en va indiquer ce que nous voullons récupérer
         * Donc en indique qu'on veut récupérer la variable $repository et en indique de c'est une 
         * AnimalRepository de base symfony fait le lien et sais qu'on veut allez récupérer un répository
         * de la class Animal cela permet de récupérer d'une façon automatique le répository qu'on pourra 
         * utilisé directement.
         */
        $animaux = $repository->findAll();
        return $this->render('animal/index.html.twig', [
            "animaux"=>$animaux
        ]);
    }

    /**
     * @Route("/animal/{id}", name="afficher_animal")
     */
    // // $id dans l'argument est récupérer pour pouvoir l'utiliser dans la fonction find afin de n'afficher
    // //que les données de l'animal ayant cet id
    // public function AfficherAnimal(AnimalRepository $repository, $id)
    // {
    //     // la variable $animal récupére l'animal ayant pour identifiant la variable $id
    //     // mais d'abord il faut faire l'injection de dépendance pour récupérer le repository lié au animaux
    //     $animal = $repository->find($id);
    //     //Envoyer l'animal récupérer par la fonction find() à la vue
    //     return $this->render('animal/animal.html.twig',[
    //         'animal'=>$animal
    //     ]);
    // }

    //Utilisation du parameteur converteur
    // Pour cela on modifier ce qui est dans l'argument de la fonction et en indique qu'on veut récupérer un animal
    // Donc on indique directement la classe après on met le paramettre et dans ce cas symfony utilise automatiquement l'id dans la route pour récupérer l'animal correspondant

    public function AfficherAnimal(Animal $animal)
    {
       return $this->render('animal/animal.html.twig',[
        'animal'=>$animal
    ]);
    }
    
}

templates/animal/animal.html.twig
{% extends 'base.html.twig' %}

{% block title %} Affichage de l'animal {% endblock %}
{% block Montitre %}Affichage de l'animal {{animal.nom}}{% endblock %}

{% block body %}
<div class="row align-item-center">
    <div class="col-2 text-center">
        <img src="{{asset('images/' ~ animal.image)}}">
    </div>
    <div class="col-auto">
        <div> Description : {{ animal.description }}</div>
        <div> Poids : {{ animal.poids }}</div>
        <div> Dangereux : 
            {% if animal.dangereux %}
                <span class="bg-danger rounded text-white">OUI</span> 
            {% else %}
                <span class="bg-success rounded text-white">NON</span> 
            {% endif %}
        </div>
        <a href="{{ path('afficher_famille',{'id': animal.famille.id}) }}" class="btn btn-primary">{{animal.famille.libelle}}</a> 
        <div>
            {% for continent in animal.continents %}
                    
                <a href="{{ path('afficher_continent', {'id':continent.id}) }}" class="btn btn-info">{{continent.libelle}}</a> 
        
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

templates/animal/famille.html.twig
{% extends 'base.html.twig' %}

{% block title %}Famille{% endblock %}
{% block Montitre %}Pages listant les familles{% endblock %}

{% block body %}

{% for famille in familles %}
<h2 class="border-bottom border-primary"> {{ famille.libelle|capitalize }} </h2>
<div>{{ famille.description }}</div>
    {% for animal in famille.animaux %}
        {{animal.nom}}
    {% endfor %}
{% endfor %}
{% endblock %}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}
{% block Montitre %}Voici la liste des animaux{% endblock %}

{% block body %}

{% for animal in animaux %}
    <div class="row align-item-center">
        <div class="col-2 text-center">
            <img src="{{asset('images/' ~ animal.image)}}">
        </div>
        <div class="col-auto">
            <h2> <a href="{{ path('afficher_animal', {'id' : animal.id }) }}"> {{ animal.nom }} </a> </h2>
            <h3>{{ animal.description }}</h3>
            <div>
                <a href="{{ path('afficher_famille',{'id': animal.famille.id}) }}" class="btn btn-primary">{{animal.famille.libelle}}</a> 
            </div>
            <h2> Présence de l'animal sur les continents :</H2>
             
                {% for continent in animal.continents %}
                
                    <a href="{{ path('afficher_continent', {'id':continent.id}) }}" class="btn btn-info">{{continent.libelle}}</a> 
                
                {% endfor %}
        </div>
        
    </div>
{% endfor %}
{% endblock %}